version: "3.9"
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/app
    tty: true
    stdin_open: true

  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=otus
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: