version: "3.9"
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:14.4-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: