source "https://rubygems.org"

# Application
gem "roda", "~> 3.58"

# Application server
gem "puma", "~> 5.6", ">= 5.6.4"

# IoC container
gem "dry-system", "~> 0.25.0"

# Code loader
gem "zeitwerk", "~> 2.6"

# Database
gem "sequel", "~> 5.58"
gem "sequel_pg", "~> 1.15"

# Dry-rb
gem "dry-view", "~> 0.7.1"
gem "dry-monads", "~> 1.4"
gem "dry-struct", "~> 1.4"
gem "dry-matcher", "~> 0.9.0"
gem "dry-validation", "~> 1.8", ">= 1.8.1"

# View rendering
gem "oj", "~> 3.13", ">= 3.13.19"
gem "jbuilder", "~> 2.11", ">= 2.11.5"
gem "tilt-jbuilder", "~> 0.7.1"

# Make-like implementation
gem "rake", "~> 13.0", ">= 13.0.6"

group :development, :test do
  gem "debug"
  gem "pry-byebug", "~> 3.9"
  gem "standard", "~> 1.14"
  gem "dotenv", "~> 2.8", ">= 2.8.1"
end

group :test do
  gem "rack-test", "~> 2.0", ">= 2.0.2"
  gem "minitest", "~> 5.16", ">= 5.16.2"
  gem "factory_bot", "~> 6.2", ">= 6.2.1"
end
