require_relative "system/otus/container"

Otus::Container.start(:database)

migrate =
  lambda do |version|
    Sequel.extension(:migration)
    Sequel::Migrator.apply(Otus::Container[:database], "db/migrate", version)

    # Rake::Task['db:dump'].invoke
  end

namespace :db do
  desc "Migrate the database."
  task :migrate do
    migrate.call(nil)
  end

  desc "Rolling back latest migration."
  task :rollback do |_, _args|
    current_version = OOtus::Container[:database].fetch("SELECT * FROM schema_info").first[:version]

    migrate.call(current_version - 1)
  end

  # desc 'Dump database schema to file.'
  # task :dump do
  #   sh %(pg_dump --schema-only --no-privileges --no-owner -s #{Otus::Container['database'].url} > db/structure.sql) if Otus::Container.development?
  # end

  # desc 'Seed database with test data.'
  # task :seed do
  #   sh %(ruby db/seeds.rb)
  # end
end

desc "Generate project documentation using yard."
task :docs do
  sh %(yard doc *.rb app/ lib/)
end
