apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: otus
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: otus
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      conntainers:
        - name: postgres
          image: postgres:14.4-alpine
          ports:
            - containerPort: 5432
              name: postgresdb
          env:
            - name: POSTGRES_DB
              value: otus-homework
            - name: POSTGRES_USER
              value: otus
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgresb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
            
