apiVersion: v1
kind: Namespace
metadata:
  name: otus

---
apiVersion: v1
kind: Secret
metadata:
  name: application-secret
  namespace: otus
type: Opaque
data:
  POSTGRES_USER: b3R1cw==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  DATABASE_URL: cG9zdGdyZXM6Ly9vdHVzOnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvb3R1c19wcm9kdWN0aW9u